#!/usr/bin/env bash
# Capture GCP agent-finops receipt evidence. Does NOT apply or destroy.
# Usage: ./scripts/capture_receipt.sh
set -euo pipefail
TF_DIR="$(cd "$(dirname "$0")/.." && pwd)"
cd "$TF_DIR"
DAY="$(date -u +%Y%m%d)"
PORTFOLIO="${ARCHITECTURE_PORTFOLIO:-$HOME/ai-architecture-portfolio}"
OUT_DIR="${GCP_RECEIPT_DIR:-$PORTFOLIO/docs/artifacts/gcp-receipts}"
mkdir -p "$OUT_DIR"
OUT="$OUT_DIR/${DAY}-finops-gcp-receipt.md"

{
  echo "# GCP agent-finops receipt — ${DAY}"
  echo
  echo "Generated by \`deploy/terraform/gcp/scripts/capture_receipt.sh\` (no apply/destroy)."
  echo
  echo "## Outputs"
  echo
  echo '```'
  terraform output 2>/dev/null || echo "(terraform output failed)"
  echo '```'
  echo
  URL="$(terraform output -raw service_url 2>/dev/null || true)"
  echo "## Health"
  echo
  if [[ -n "$URL" ]]; then
    echo '```'
    curl -sS --max-time 60 "${URL%/}/health" | head -c 800 || echo "(curl failed)"
    echo
    echo '```'
  else
    echo "_No service_url_"
  fi
  echo
  echo "## Meter smoke (optional)"
  echo
  echo "If API key configured:"
  echo '```'
  echo "curl -sS -X POST \"\$SERVICE_URL/v1/usage\" -H \"X-API-Key: \$KEY\" -H 'Content-Type: application/json' \\"
  echo "  -d '{\"scope_type\":\"agent\",\"scope_value\":\"receipt\",\"provider\":\"openai\",\"model\":\"gpt-4o-mini\",\"prompt_tokens\":10,\"completion_tokens\":5}'"
  echo '```'
  echo
  echo "## Teardown"
  echo
  echo "- [ ] \`terraform destroy -var=project_id=... -var=region=...\` **same day**"
  echo "- [ ] Or Cloud SQL instance **stopped** if destroy deferred"
  echo "- [ ] Budget alert on project confirmed"
} >"$OUT"

echo "Wrote $OUT"
echo "See ai-architecture-portfolio/docs/P2_GCP_RECEIPT_RUNBOOK.md"
